---
include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - test
  - build
  - push

workflow:
  auto_cancel:
    on_new_commit: interruptible
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

.go-cache:
  image: docker.io/library/golang:1.25-alpine
  tags:
    - shared-podman
  before_script:
    - apk add --no-cache git make bash
    - go get github.com/boumenot/gocover-cobertura
  cache:
    paths:
      - /go/pkg/mod/

.buildah:
  image: docker.io/library/golang:1.25-alpine
  variables:
    IMAGE_TAG_BASE: quay.io/rhdl/operator
    STORAGE_DRIVER: vfs  # Use vfs for buildah
    REGISTRY_AUTH_FILE: "${QUAY_REGISTRY_AUTH_FILE}"
    CONTAINER_TOOL: buildah
    GIT_VERSION: "-git${CI_COMMIT_SHA}"
  stage: build
  tags:
    - shared-podman
  before_script:
    - apk add --no-cache buildah git make bash
    - buildah --version
    - buildah images
  after_script:
    - buildah images

bundle-build:
  extends: .buildah
  script:
    - make bundle-build

docker-build:
  extends: .buildah
  script:
    - make docker-build

catalog-build:
  extends: .buildah
  script:
    - make catalog-build

go-build:
  stage: build
  extends: .go-cache
  script:
    - make build

go-test:
  stage: test
  extends: .go-cache
  script:
    - make test
    - go tool cover -func=cover.out
    - go run github.com/boumenot/gocover-cobertura < cover.out > coverage.xml
  coverage: '/\(statements\)(?:\s+)?(\d+(?:\.\d+)?%)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

sast:
  stage: test
  tags:
    - shared-podman