---
include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - test
  - build
  - push
  - promote

workflow:
  auto_cancel:
    on_new_commit: interruptible
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

.go-cache:
  image: docker.io/library/golang:1.24-alpine
  tags:
    - shared-podman
  before_script:
    - apk add --no-cache git make bash
    - go get github.com/boumenot/gocover-cobertura
  cache:
    paths:
      - /go/pkg/mod/

.buildah:
  image: quay.io/rhdl/builder:latest
  variables:
    IMAGE_TAG_BASE: quay.io/rhdl/operator
    STORAGE_DRIVER: vfs  # Use vfs for buildah
    REGISTRY_AUTH_FILE: "${QUAY_REGISTRY_AUTH_FILE}"
    CONTAINER_TOOL: buildah
  stage: push
  tags:
    - shared-podman
  before_script:
    - dnf --assumeyes --refresh install golang
    - buildah --version
    - buildah images
  after_script:
    - buildah images

.skopeo:
  image: quay.io/rhdl/builder:latest
  variables:
    IMAGE_TAG_BASE: quay.io/rhdl/operator
    STORAGE_DRIVER: vfs  # Use vfs for buildah
    REGISTRY_AUTH_FILE: "${QUAY_REGISTRY_AUTH_FILE}"
    SNAPSHOT: "-git${CI_COMMIT_SHORT_SHA}"
  stage: promote
  tags:
    - shared-podman
  before_script:
    - skopeo --version

docker-build-and-push:
  extends: .buildah
  variables:
    SNAPSHOT: "-git${CI_COMMIT_SHORT_SHA}"
  script:
    - make docker-build docker-push

docker-promote:
  extends: .skopeo
  script:
    - >
      skopeo copy
      docker://${IMAGE_TAG_BASE}:$(make full-version)
      docker://${IMAGE_TAG_BASE}:$(make version)

go-build:
  stage: build
  extends: .go-cache
  script:
    - make build

go-test:
  stage: test
  extends: .go-cache
  script:
    - make test
    - go tool cover -func=cover.out
    - go run github.com/boumenot/gocover-cobertura < cover.out > coverage.xml
  coverage: '/\(statements\)(?:\s+)?(\d+(?:\.\d+)?%)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

sast:
  stage: test
  tags:
    - shared-podman
