---
repos:
  - repo: local
    hooks:
      - id: go-mod-tidy
        name: go mod tidy
        description: Ensures go.mod and go.sum are up to date
        entry: go mod tidy
        language: system
        files: '^go\.(mod|sum)$|\.go$'
        pass_filenames: false
        stages: [pre-commit]
