---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - rhdl.distributed-ci.io
  resources:
  - downloaders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rhdl.distributed-ci.io
  resources:
  - downloaders/finalizers
  verbs:
  - update
- apiGroups:
  - rhdl.distributed-ci.io
  resources:
  - downloaders/status
  verbs:
  - get
  - patch
  - update
