apiVersion: v1
kind: Secret
metadata:
  name: test-credentials
  namespace: default
type: Opaque
data:
  RHDL_ACCESS_KEY: dGVzdC1hY2Nlc3Mta2V5  # test-access-key (base64 encoded)
  RHDL_SECRET_KEY: dGVzdC1zZWNyZXQta2V5  # test-secret-key (base64 encoded)
---
apiVersion: rhdl.distributed-ci.io/v1alpha1
kind: Downloader
metadata:
  labels:
    app.kubernetes.io/name: rhdl-operator
    app.kubernetes.io/managed-by: kustomize
  name: downloader-sample
spec:
  topic: RHEL-9.2
  persistentVolumeClaim: pvc
  credentials: test-credentials
