apiVersion: rhdl.distributed-ci.io/v1alpha1
kind: Downloader
metadata:
  labels:
    app.kubernetes.io/name: rhdl-operator
    app.kubernetes.io/managed-by: kustomize
  name: downloader-sample
spec:
  # TODO(user): Add fields here
