name: Container Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG_BASE: quay.io/rhdl/operator
      CONTAINER_TOOL: buildah

    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install buildah
        run: |
          sudo apt-get update
          sudo apt-get install -y buildah

      - name: Login to quay.io
        run: |
          echo ${{ secrets.RHDL_QUAY_PASSWORD }} | buildah login -u ${{ secrets.RHDL_QUAY_USER }} --password-stdin

      - name: Build and push docker image
        run: |
          make docker-build docker-push SNAPSHOT="-git${GITHUB_SHA:0:7}"
