name: Container snapshot

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    container:
      image: quay.io/rhdl/builder:latest
      env:
        IMAGE_TAG_BASE: quay.io/rhdl/operator
        STORAGE_DRIVER: vfs
        CONTAINER_TOOL: buildah
        BUILDAH_ISOLATION: chroot

    steps:
      - name: Install Go
        run: |
          dnf --assumeyes --refresh install golang

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build docker image
        run: |
          pwd
          ls -l
          make docker-build SNAPSHOT=${GITHUB_SHA:0:7}
