name: Container snapshot

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG_BASE: quay.io/rhdl/operator
      CONTAINER_TOOL: buildah

    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install buildah
        run: |
          sudo apt-get update
          sudo apt-get install -y buildah

      - name: Build docker image
        run: |
          pwd
          ls -l
          make docker-build SNAPSHOT="-git${GITHUB_SHA:0:7}"
